### ISSUE TITLE
Slashes in `cd` command are URL-encoded

### ISSUE THREAD

**Issue by ferenczy** [htty/htty#123] opened 2015-03-24 16:04 UTC
Hi,

if I'm trying to `cd` to a path consisting of more parts delimited by slashes (/), but slashes are URL encoded (to `%2F`), so request obviously doesn't work than. Therefore I have to execute `cd` for each part of path individually. That means I have to do for example this:

```
http://example.com/> cd test
http://example.com/test> cd test2
http://example.com/test/test2>
```

...instead of simply:

`http://example.com> cd test/test2`

...because that would produce this:

`http://example.com/test%2Ftest2>`

I saw `cd` with multi-part path in your examples, so I wonder why it doesn't work for me. I'm using **htty 1.5.0** under 64bit Cygwin on Windows.

**Comment by njonsson** [comment] 2015-03-24 18:47
I’ve reproduced this. I think this is a regression because, as you point out, even the example usage of `cd ../../foo` URL-encodes the slashes.

**Comment by ferenczy** [comment] 2015-03-26 10:54
Great, thank you.

*even the example usage of `cd ../../foo` URL-encodes the slashes*

No, I didn't see URL encoding in any of your examples. The point is that it works right in your examples, **without** URL encoding of slashes.

Anyway I like your application. I like it more than [http-console](https://github.com/cloudhead/http-console/). I think I'll learn Ruby a bit, because it seems you're not developing it anymore. Do you accept pull requests? I have a lot of ideas how to improve it. For example I like JSON syntax highlighting of http-console etc.

**Comment by njonsson** [comment] 2015-03-26 14:00
Yes, pull requests are welcome. Thanks for your interest!

**Comment by pepijnve** [comment] 2015-09-14 09:44
I'm seeing this as well.
```
pepijn$ htty foobar
*** Welcome to  htty , the HTTP TTY. Heck To The Yeah!
http://foobar/> cd /a/b
http://foobar/%2Fa%2Fb> 
```

I had a quick look at the code and it seems like the single argument to `cd` is passed directly to the URL escaping function (https://github.com/htty/htty/blob/master/lib/htty/cli/commands/path_set.rb#L51). Is that correct or is there code that splits the path into components elsewhere?

**Comment by pepijnve** [comment] 2015-09-14 11:03
I had a look at things at runtime with the debugger and that confirmed what was going wrong. The referenced PR splits the input path on `/` characters, URL escapes each component separately and then joins the parts with `/`s again.
The only downside to this change I can see is that if you'll have to manually escape `/` characters. Doesn't seem like a bad tradeoff to me.

**Comment by pepijnve** [comment] 2015-09-14 11:08
Note that I intentionally did not use the `sanitize_arguments` hook from Command to do the splitting. The multi-part path is logically still one argument and it didn't seem to make sense to me to split it into multiple arguments.
In 1.5.0 cd with multiple arguments has the following behaviour
``` 
http://0.0.0.0/> cd foo bar
*** Wrong number of arguments (2 for 1)
```
With the reference PR all but the first argument is ignored silently.

**Comment by pepijnve** [comment] 2015-09-14 11:28
The initial commit in my PR had the URL escaping in `PathSet#perform` as in the 1.5.0 version. I've moved that to the `sanitise_arguments` hook instead to make it easier to write specs for this change.

**Comment by njonsson** [comment] 2015-10-21 00:09
Fixed in https://github.com/htty/htty/pull/127. Thanks, @pepijnve!

**Closed by njonsson** 2015-10-21 00:09 UTC
Labels: class:defect, concern:core, priority:high
